/// <reference types="vitest/config" />
// vite.config.ts — build, dev-server, PWA, and test configuration.
// The VitePWA plugin generates the web app manifest and service worker that
// make StackTrack installable; icons are generated by scripts/generate-icons.mjs.
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // autoUpdate: new versions activate on next visit without a prompt —
      // right choice while the app is single-user and pre-1.0.
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg'],
      manifest: {
        name: 'StackTrack',
        short_name: 'StackTrack',
        description:
          'Track your medication & supplement stack and daily metrics.',
        theme_color: '#0f766e',
        background_color: '#f8fafc',
        display: 'standalone',
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'pwa-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
  test: {
    environment: 'jsdom',
    setupFiles: ['tests/setup.ts'],
    // Sequential files: parallel workers intermittently starve user-event
    // timing in the busiest UI tests (proven env-level, not an app bug —
    // see DECISION_LOG 2026-06-12). Costs ~10s of wall clock, buys
    // deterministic runs locally and on 2-core CI runners.
    fileParallelism: false,
  },
})
